# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editPost.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(70, 195, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(70, 125, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 15, 160, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sortEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.sortEdit.setObjectName("sortEdit")
        self.verticalLayout.addWidget(self.sortEdit)
        self.fryEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.fryEdit.setObjectName("fryEdit")
        self.verticalLayout.addWidget(self.fryEdit)
        self.formEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.formEdit.setObjectName("formEdit")
        self.verticalLayout.addWidget(self.formEdit)
        self.tasteEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tasteEdit.setObjectName("tasteEdit")
        self.verticalLayout.addWidget(self.tasteEdit)
        self.priceEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.priceEdit.setObjectName("priceEdit")
        self.verticalLayout.addWidget(self.priceEdit)
        self.weightEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.weightEdit.setObjectName("weightEdit")
        self.verticalLayout.addWidget(self.weightEdit)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(130, 245, 141, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 55, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(70, 160, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 90, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "Вес"))
        self.label.setText(_translate("Dialog", "Сорт"))
        self.label_4.setText(_translate("Dialog", "Вкус"))
        self.pushButton.setText(_translate("Dialog", "Сохранить изменения"))
        self.label_2.setText(_translate("Dialog", "Обжарка"))
        self.label_5.setText(_translate("Dialog", "Цена"))
        self.label_3.setText(_translate("Dialog", "Форма"))
